### ISSUE TITLE
Performed the instructions to try this example but got Error: Cannot find module 'express'

### ISSUE THREAD

**Issue by nickweavers** [microsoft/vscode-remote-try-node#10]
I performed the instructions to try this example but got Error: Cannot find module 'express'
```
/usr/bin/node --inspect-brk=35421 server.js
Debugger listening on ws://127.0.0.1:35421/0330b091-2d91-47c2-be20-d845f67a1ba9
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
Waiting for the debugger to disconnect...
Error: Cannot find module 'express'
Require stack:
- /home/nickw/vscode-remote-try-node/server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:957:15)
    at Function.Module._load (internal/modules/cjs/loader.js:840:27)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/home/nickw/vscode-remote-try-node/server.js:8:17)
    at Module._compile (internal/modules/cjs/loader.js:1130:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
```

- VSCode Version: 1.45.1 (system setup)
Commit: 5763d90
Date: 2020-05-14T08:27:35.169Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0

- OS: Windows_NT x64 10.0.18363
OS Version:
Windows 10 Pro
Version 1909
Installed on 21/08/2019
OS build 18363.836

**Comment by Chuxel** [comment]
For some reason the `yarn install` must not have completed successfully.  Can you try running it from an integrated terminal and see if it resolves the problem?

**Comment by nickweavers** [comment]
Hi @chuxel, thanks for responding.
I just started from scratch and cloned the repo to ``/c/var/www/lambda/vscode-remote-try-node``
then with server.js open I pressed F1 as per the instructions in the README.md. 
The instructions said I should then choose the  ``Remote-Containers: Open Folder in Container...`` command, but these are the only selections I see under ``Remote-Containers:``
![image](https://user-images.githubusercontent.com/194136/82152847-f8182800-985b-11ea-8769-a143726c1d6b.png)
Should I choose ``Remote-Containers: Rebuild and Reopen in Container``. I think this is what I did last time before continuing, but why do the instructions differ from what I see?

**Comment by Chuxel** [comment]
You are in WSL, so the instructions are slightly different.  I can update them given that.  If you'd done this from the Windows side, the command would be present.

**Comment by Chuxel** [comment]
Use reopen in container instaed.

**Comment by nickweavers** [comment]
If I do that, then it appears to work in that the code runs up to the break point on line 20 and I can see the contents of variables when I hover over them, but when click run to  continue and get the message
```
/usr/local/bin/node --inspect-brk=40926 server.js
Debugger listening on ws://127.0.0.1:40926/00f91ca2-2bc3-4636-a1d2-119b747e2257
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
Running on http://0.0.0.0:3000
```
the following command run in wsl does not return. Oddly it doesn't even timoute.
```
nickw@nicks-xps-15-9560:/c/var/www/lambda/vscode-remote-try-node
$ curl http://0.0.0.0:3000
```

**Comment by Chuxel** [comment]
It is being forwarded to where VS Code is running - which is on the Windows side.  If you use the integrated terminal once you've repoend in a container, you'll be inside the container itself which will work.  A browser in Windows will also work (as would curl if installed).  In WSL, localhost will resolve to the WSL instance.  If you use `curl` with your Windows IP, you will see it works.

**Comment by Chuxel** [comment]
Closing as stale issue.
