### ISSUE TITLE
How to use these devcontainer file without loosing docker ?

### ISSUE THREAD

**Issue by anirugu** [microsoft/vscode-remote-try-node#19]
Hi @Chuxel 

I started using the .devcontainer settings from this repos after reading your comment here https://github.community/t/not-able-to-install-yarn-and-angular-cli-and-create-codespace-container/159239/3

I later found that I am not able to do use docker in container. Today I remove the .devcontainer and build again now I am able to use docker.

I am only looking for install cli and do npm install after the container create. I don't want to use .devcontainer file since it will not provide me docker but I want to apply postcreatecommand. Any help with that!

for example look at this commit https://github.com/yegasi/yegasi.github.io/commit/6b4762399f89a572e047df4cc39c66419fe77c7b I am only looking for applying the postcreatecommand.

**Comment by anirugu** [comment]
In some other words, how we can use devcontainer for postcreatecommand without dockerfile.

**Comment by Chuxel** [comment]
@anirugu - You can use the docker-debian.sh or docker-in-docker-debian.sh scripts to add docker to your own custom config.

https://github.com/microsoft/vscode-dev-containers/blob/master/script-library/docs/docker-in-docker.md
https://github.com/microsoft/vscode-dev-containers/blob/master/script-library/docs/docker.md

The default codespaces image uses Docker-in-Docker.
